spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC

server:
  port: 8081

mybatis:
  type-aliases-package: com.xzy.myblogbackground.model
  configuration:
    map-underscore-to-camel-case: true
